### ISSUE TITLE
`async for` does not work with `Inotify.close()`

### ISSUE THREAD

**Issue by elbaro** [absperf/asyncinotify#3] opened 2023-11-29 11:53 UTC
```py
async def run2():
    n = None

    async def loop():
        nonlocal n
        assert n

        try:
            async for ev in n:
                print(ev)
        except asyncio.CancelledError:
            pass

    n = Inotify()
    n.add_watch(
        f"myfile.txt",
        # Mask.ACCESS | Mask.MODIFY | Mask.CREATE | Mask.MOVE,
        Mask.ACCESS
        | Mask.MODIFY
        | Mask.OPEN
        | Mask.CREATE
        | Mask.DELETE
        | Mask.ATTRIB
        | Mask.CLOSE
        | Mask.MOVE,
    )
    task = asyncio.create_task(loop())
    await asyncio.sleep(10)
    n.close()
    task.cancel()

    n = Inotify()
    n.add_watch(
        f"myfile.txt",
        # Mask.ACCESS | Mask.MODIFY | Mask.CREATE | Mask.MOVE,
        Mask.ACCESS
        | Mask.MODIFY
        | Mask.OPEN
        | Mask.CREATE
        | Mask.DELETE
        | Mask.ATTRIB
        | Mask.CLOSE
        | Mask.MOVE,
    )
    task = asyncio.create_task(loop())
    await asyncio.sleep(10)
    n.close()
    task.cancel()


asyncio.run(run2())
```

`inotify.close()` raises an exception from `async for event in inotify:`. Then, the second Inotify() instance does not yield any event.

**Comment by Taywee** [comment] 2023-11-29 16:09
I can verify that this happens.  The first inotify throwing an exception is expected (though it should be a cancellation exception; it's picking up a different one along the way).  The second one not yielding any events is a real concern, and honestly a little confusing.  This library doesn't keep global state, so the second inotify instance should be completely independent of the first.

**Comment by Taywee** [comment] 2023-11-29 16:18
Doing a small amount of testing, I think this might be caused by the fd being the same between the two inotify instances.  I think the first instance is being deleted by the GC, causing it to close the second instance.  If I print the inotify instance fds, they both are assigned the same number in my tests.

**Comment by Taywee** [comment] 2023-11-29 19:43
Some more debugging makes this look much more strange.  `add_reader` seems to possibly not work right with inotify.  It simply never fires that the fd is ready to give events.  I've tried a couple different configurations, and it seems like it works to some degree if I create the second inotify instance before closing the first, but not reliably.

**Comment by elbaro** [comment] 2023-11-29 20:50
On Windows, even select only supports the socket: https://docs.python.org/3/library/select.html

A single thread for multiple watches sounds not that bad. Better than not working.

**Comment by Taywee** [comment] 2023-11-29 21:13
True, but I don't really care about Windows here; inotify is a Linux-only API in the first place.  I've avoided it with an epoll FD, which seems to work fine.  Version 4.0.3 should fix this bug, along with the weird cancellation error, and I've put an appropriate test case in.

As an aside, you should never swallow CancelledError in tasks.  If you catch it, it should always be re-raised.  Swallowing CancelledError can cause problems.  Your example exposed a bug where this library was accidentally swallowing it when it was trying to work with an already-closed fd.

Thanks for the bug report and useful example.  I'm closing this because the new version doesn't replicate the problem anymore.  Feel free to open another issue if you find any more, or if it's still not working on your side.

**Closed by Taywee** 2023-11-29 21:13 UTC
Labels: bug
